name: CI CD

on:
  push:
    branches: [main]

env:
  IMAGE_NAME: ayushmartin/team-management:latest

jobs:
  # ---- frontend ----
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Write frontend env
        run: echo "${{ secrets.FRONTEND_ENV }}" > frontend/.env

      - name: install dependencies
        run: npm install
        working-directory: frontend

      - name: build
        run: npm run build
        working-directory: frontend

  deploy-frontend:
    needs: build-frontend
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: install vercel
        run: npm install -g vercel

      - name: Deploy to Vercel
        working-directory: frontend
        run: vercel --prod --yes --token=${{ secrets.VERCEL_TOKEN }} --name team-management

  # ---- backend ----
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Write env for build
        run: |
          echo "${{ secrets.BACKEND_ENV }}" > backend/.env

      - name: install dependencies
        run: npm install
        working-directory: backend

      - name: build
        run: npm run build
        working-directory: backend

  push-backend-to-docker-hub:
    needs: build-backend
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build docker image
        run: docker build -t $IMAGE_NAME ./backend

      - name: push docker image to docker hub
        run: docker push $IMAGE_NAME

  deploy-backend:
    needs: push-backend-to-docker-hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Write .env file from GitHub Secrets
        run: echo "${{ secrets.BACKEND_ENV }}" > .env

      - name: Copy deployment files to EXC
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          source: "backend/docker-compose.yaml,backend/.env,backend/deploy.sh"
          target: "~/team-management"

      - name: Run deploy.sh on EXC
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            ls
            cd ~/team-management/backend
            ls
            chmod +x deploy.sh
            ./deploy.sh
